#################################################
# Gest configurations
#################################################
---
- hosts: proc
  become: yes
  vars_files:
    - group_vars/baremetal_hosts

  tasks:
    # - name: Creates directory
    #   become: yes
    #   file:
    #     path: /var/www/html/proclab
    #     state: directory
    #     owner: vagrant
    #     group: vagrant
    #     mode: 0775
    #     recurse: yes

    # - name: composer create-project drupal/recommended-project:9.5.3 proclab
    #   shell: "composer create-project drupal/recommended-project:9.5.3 proclab"
    #   args:
    #     chdir: /var/www/html/proclab
    #   register: out
    # - debug: var=out.stdout_lines

    # http://localhost:8181/proclab/proclab/web/core/INSTALL.txt
    - name: Create settings.php
      ansible.builtin.copy:
        remote_src: yes
        src: /var/www/html/proclab/proclab/web/sites/default/default.settings.php
        dest: /var/www/html/proclab/proclab/web/sites/default/settings.php
        owner: vagrant
        group: vagrant
        mode: 'a+w'

    # - composer:
    #     command: create-project
    #     arguments: drupal/recommended-project:9.5.3 proclab
    #     working_dir: /var/www/html/proclab    